/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  DexhuneConfig,
  DexhuneConfigInterface,
} from "../../DexhuneRoot.sol/DexhuneConfig";

const _abi = [
  {
    inputs: [],
    name: "cooldownTimeout",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "transferCooldown",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405260016000806101000a81548160ff021916908315150217905550603c600261002c919061007a565b60015534801561003b57600080fd5b506100bc565b6000819050919050565b7f4e487b7100000000000000000000000000000000000000000000000000000000600052601160045260246000fd5b600061008582610041565b915061009083610041565b925082820261009e81610041565b915082820484148315176100b5576100b461004b565b5b5092915050565b61011a806100cb6000396000f3fe6080604052348015600f57600080fd5b506004361060325760003560e01c806368f16293146037578063bbf79246146051575b600080fd5b603d606b565b60405160489190609b565b60405180910390f35b6057607c565b6040516062919060cb565b60405180910390f35b60008054906101000a900460ff1681565b60015481565b60008115159050919050565b6095816082565b82525050565b600060208201905060ae6000830184608e565b92915050565b6000819050919050565b60c58160b4565b82525050565b600060208201905060de600083018460be565b9291505056fea2646970667358221220dcb70610ca6134845c9e64b24d749a55a3c82761502df1a0c0315a75a743f51c64736f6c63430008150033";

type DexhuneConfigConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: DexhuneConfigConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class DexhuneConfig__factory extends ContractFactory {
  constructor(...args: DexhuneConfigConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      DexhuneConfig & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): DexhuneConfig__factory {
    return super.connect(runner) as DexhuneConfig__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): DexhuneConfigInterface {
    return new Interface(_abi) as DexhuneConfigInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): DexhuneConfig {
    return new Contract(address, _abi, runner) as unknown as DexhuneConfig;
  }
}
