/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { IPriceDAO, IPriceDAOInterface } from "../../interfaces/IPriceDAO";

const _abi = [
  {
    inputs: [],
    name: "getPrice",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IPriceDAO__factory {
  static readonly abi = _abi;
  static createInterface(): IPriceDAOInterface {
    return new Interface(_abi) as IPriceDAOInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IPriceDAO {
    return new Contract(address, _abi, runner) as unknown as IPriceDAO;
  }
}
