/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as dexhuneExchangeSol from "./DexhuneExchange.sol";
export type { dexhuneExchangeSol };
export type { DexhuneExchangeBase } from "./DexhuneExchangeBase";
