/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IERC721Proxy,
  IERC721ProxyInterface,
} from "../../DexhunePriceDAO.sol/IERC721Proxy";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
    ],
    name: "balanceOf",
    outputs: [
      {
        internalType: "uint256",
        name: "balance",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IERC721Proxy__factory {
  static readonly abi = _abi;
  static createInterface(): IERC721ProxyInterface {
    return new Interface(_abi) as IERC721ProxyInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IERC721Proxy {
    return new Contract(address, _abi, runner) as unknown as IERC721Proxy;
  }
}
