/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { DexhuneERC20__factory } from "./DexhuneERC20__factory";
export { IERC20__factory } from "./IERC20__factory";
