/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace DexhuneBase {
  export type PriceProposalStruct = {
    description: string;
    value: string;
    votesUp: BigNumberish;
    votesDown: BigNumberish;
    finalized: boolean;
  };

  export type PriceProposalStructOutput = [
    description: string,
    value: string,
    votesUp: bigint,
    votesDown: bigint,
    finalized: boolean
  ] & {
    description: string;
    value: string;
    votesUp: bigint;
    votesDown: bigint;
    finalized: boolean;
  };
}

export interface DexhunePriceDAOInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "NFTCollections"
      | "PriceProposals"
      | "addNFTCollection"
      | "cooldownTimeout"
      | "currentProposal"
      | "finalizeProposal"
      | "getPrice"
      | "owner"
      | "proposalExpiresAt"
      | "proposePrice"
      | "removeNFTCollection"
      | "setCooldownTimeout"
      | "setTransferTimeout"
      | "transferCooldown"
      | "transferOwnership"
      | "voteDown"
      | "voteUp"
      | "votingEndsAt"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "PriceUpdated"
      | "ProposalCreated"
      | "ProposalFinalized"
      | "VotedDown"
      | "VotedUp"
      | "addedNFTCollection"
      | "removedNFTCollection"
      | "transferredOwnership"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "NFTCollections",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "PriceProposals",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "addNFTCollection",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "cooldownTimeout",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "currentProposal",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeProposal",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getPrice", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "proposalExpiresAt",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proposePrice",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "removeNFTCollection",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setCooldownTimeout",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTransferTimeout",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "transferCooldown",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "voteDown", values?: undefined): string;
  encodeFunctionData(functionFragment: "voteUp", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "votingEndsAt",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "NFTCollections",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PriceProposals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addNFTCollection",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cooldownTimeout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPrice", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proposalExpiresAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proposePrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeNFTCollection",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCooldownTimeout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTransferTimeout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferCooldown",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "voteDown", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "voteUp", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "votingEndsAt",
    data: BytesLike
  ): Result;
}

export namespace PriceUpdatedEvent {
  export type InputTuple = [oldPrice: string, newPrice: string];
  export type OutputTuple = [oldPrice: string, newPrice: string];
  export interface OutputObject {
    oldPrice: string;
    newPrice: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalCreatedEvent {
  export type InputTuple = [
    id: BigNumberish,
    description: string,
    proposer: AddressLike
  ];
  export type OutputTuple = [id: bigint, description: string, proposer: string];
  export interface OutputObject {
    id: bigint;
    description: string;
    proposer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalFinalizedEvent {
  export type InputTuple = [id: BigNumberish, passed: boolean];
  export type OutputTuple = [id: bigint, passed: boolean];
  export interface OutputObject {
    id: bigint;
    passed: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VotedDownEvent {
  export type InputTuple = [voter: AddressLike, proposalId: BigNumberish];
  export type OutputTuple = [voter: string, proposalId: bigint];
  export interface OutputObject {
    voter: string;
    proposalId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VotedUpEvent {
  export type InputTuple = [voter: AddressLike, proposalId: BigNumberish];
  export type OutputTuple = [voter: string, proposalId: bigint];
  export interface OutputObject {
    voter: string;
    proposalId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace addedNFTCollectionEvent {
  export type InputTuple = [id: BigNumberish, collectionAddress: AddressLike];
  export type OutputTuple = [id: bigint, collectionAddress: string];
  export interface OutputObject {
    id: bigint;
    collectionAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace removedNFTCollectionEvent {
  export type InputTuple = [id: BigNumberish, collectionAddress: AddressLike];
  export type OutputTuple = [id: bigint, collectionAddress: string];
  export interface OutputObject {
    id: bigint;
    collectionAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace transferredOwnershipEvent {
  export type InputTuple = [from: AddressLike, to: AddressLike];
  export type OutputTuple = [from: string, to: string];
  export interface OutputObject {
    from: string;
    to: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DexhunePriceDAO extends BaseContract {
  connect(runner?: ContractRunner | null): DexhunePriceDAO;
  waitForDeployment(): Promise<this>;

  interface: DexhunePriceDAOInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  NFTCollections: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  PriceProposals: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, boolean] & {
        description: string;
        value: string;
        votesUp: bigint;
        votesDown: bigint;
        finalized: boolean;
      }
    ],
    "view"
  >;

  addNFTCollection: TypedContractMethod<
    [_contractAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  cooldownTimeout: TypedContractMethod<[], [bigint], "view">;

  currentProposal: TypedContractMethod<
    [],
    [DexhuneBase.PriceProposalStructOutput],
    "view"
  >;

  finalizeProposal: TypedContractMethod<[], [void], "nonpayable">;

  getPrice: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  proposalExpiresAt: TypedContractMethod<[], [bigint], "view">;

  proposePrice: TypedContractMethod<
    [_desc: string, _price: string],
    [void],
    "nonpayable"
  >;

  removeNFTCollection: TypedContractMethod<
    [_index: BigNumberish],
    [void],
    "nonpayable"
  >;

  setCooldownTimeout: TypedContractMethod<
    [_timeout: BigNumberish],
    [void],
    "nonpayable"
  >;

  setTransferTimeout: TypedContractMethod<
    [_enabled: boolean],
    [void],
    "nonpayable"
  >;

  transferCooldown: TypedContractMethod<[], [boolean], "view">;

  transferOwnership: TypedContractMethod<
    [_address: AddressLike],
    [void],
    "nonpayable"
  >;

  voteDown: TypedContractMethod<[], [void], "nonpayable">;

  voteUp: TypedContractMethod<[], [void], "nonpayable">;

  votingEndsAt: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "NFTCollections"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "PriceProposals"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, boolean] & {
        description: string;
        value: string;
        votesUp: bigint;
        votesDown: bigint;
        finalized: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "addNFTCollection"
  ): TypedContractMethod<[_contractAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "cooldownTimeout"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "currentProposal"
  ): TypedContractMethod<[], [DexhuneBase.PriceProposalStructOutput], "view">;
  getFunction(
    nameOrSignature: "finalizeProposal"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getPrice"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "proposalExpiresAt"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "proposePrice"
  ): TypedContractMethod<[_desc: string, _price: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeNFTCollection"
  ): TypedContractMethod<[_index: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setCooldownTimeout"
  ): TypedContractMethod<[_timeout: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTransferTimeout"
  ): TypedContractMethod<[_enabled: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferCooldown"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[_address: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "voteDown"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "voteUp"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "votingEndsAt"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "PriceUpdated"
  ): TypedContractEvent<
    PriceUpdatedEvent.InputTuple,
    PriceUpdatedEvent.OutputTuple,
    PriceUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ProposalCreated"
  ): TypedContractEvent<
    ProposalCreatedEvent.InputTuple,
    ProposalCreatedEvent.OutputTuple,
    ProposalCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ProposalFinalized"
  ): TypedContractEvent<
    ProposalFinalizedEvent.InputTuple,
    ProposalFinalizedEvent.OutputTuple,
    ProposalFinalizedEvent.OutputObject
  >;
  getEvent(
    key: "VotedDown"
  ): TypedContractEvent<
    VotedDownEvent.InputTuple,
    VotedDownEvent.OutputTuple,
    VotedDownEvent.OutputObject
  >;
  getEvent(
    key: "VotedUp"
  ): TypedContractEvent<
    VotedUpEvent.InputTuple,
    VotedUpEvent.OutputTuple,
    VotedUpEvent.OutputObject
  >;
  getEvent(
    key: "addedNFTCollection"
  ): TypedContractEvent<
    addedNFTCollectionEvent.InputTuple,
    addedNFTCollectionEvent.OutputTuple,
    addedNFTCollectionEvent.OutputObject
  >;
  getEvent(
    key: "removedNFTCollection"
  ): TypedContractEvent<
    removedNFTCollectionEvent.InputTuple,
    removedNFTCollectionEvent.OutputTuple,
    removedNFTCollectionEvent.OutputObject
  >;
  getEvent(
    key: "transferredOwnership"
  ): TypedContractEvent<
    transferredOwnershipEvent.InputTuple,
    transferredOwnershipEvent.OutputTuple,
    transferredOwnershipEvent.OutputObject
  >;

  filters: {
    "PriceUpdated(string,string)": TypedContractEvent<
      PriceUpdatedEvent.InputTuple,
      PriceUpdatedEvent.OutputTuple,
      PriceUpdatedEvent.OutputObject
    >;
    PriceUpdated: TypedContractEvent<
      PriceUpdatedEvent.InputTuple,
      PriceUpdatedEvent.OutputTuple,
      PriceUpdatedEvent.OutputObject
    >;

    "ProposalCreated(uint256,string,address)": TypedContractEvent<
      ProposalCreatedEvent.InputTuple,
      ProposalCreatedEvent.OutputTuple,
      ProposalCreatedEvent.OutputObject
    >;
    ProposalCreated: TypedContractEvent<
      ProposalCreatedEvent.InputTuple,
      ProposalCreatedEvent.OutputTuple,
      ProposalCreatedEvent.OutputObject
    >;

    "ProposalFinalized(uint256,bool)": TypedContractEvent<
      ProposalFinalizedEvent.InputTuple,
      ProposalFinalizedEvent.OutputTuple,
      ProposalFinalizedEvent.OutputObject
    >;
    ProposalFinalized: TypedContractEvent<
      ProposalFinalizedEvent.InputTuple,
      ProposalFinalizedEvent.OutputTuple,
      ProposalFinalizedEvent.OutputObject
    >;

    "VotedDown(address,uint256)": TypedContractEvent<
      VotedDownEvent.InputTuple,
      VotedDownEvent.OutputTuple,
      VotedDownEvent.OutputObject
    >;
    VotedDown: TypedContractEvent<
      VotedDownEvent.InputTuple,
      VotedDownEvent.OutputTuple,
      VotedDownEvent.OutputObject
    >;

    "VotedUp(address,uint256)": TypedContractEvent<
      VotedUpEvent.InputTuple,
      VotedUpEvent.OutputTuple,
      VotedUpEvent.OutputObject
    >;
    VotedUp: TypedContractEvent<
      VotedUpEvent.InputTuple,
      VotedUpEvent.OutputTuple,
      VotedUpEvent.OutputObject
    >;

    "addedNFTCollection(uint256,address)": TypedContractEvent<
      addedNFTCollectionEvent.InputTuple,
      addedNFTCollectionEvent.OutputTuple,
      addedNFTCollectionEvent.OutputObject
    >;
    addedNFTCollection: TypedContractEvent<
      addedNFTCollectionEvent.InputTuple,
      addedNFTCollectionEvent.OutputTuple,
      addedNFTCollectionEvent.OutputObject
    >;

    "removedNFTCollection(uint256,address)": TypedContractEvent<
      removedNFTCollectionEvent.InputTuple,
      removedNFTCollectionEvent.OutputTuple,
      removedNFTCollectionEvent.OutputObject
    >;
    removedNFTCollection: TypedContractEvent<
      removedNFTCollectionEvent.InputTuple,
      removedNFTCollectionEvent.OutputTuple,
      removedNFTCollectionEvent.OutputObject
    >;

    "transferredOwnership(address,address)": TypedContractEvent<
      transferredOwnershipEvent.InputTuple,
      transferredOwnershipEvent.OutputTuple,
      transferredOwnershipEvent.OutputObject
    >;
    transferredOwnership: TypedContractEvent<
      transferredOwnershipEvent.InputTuple,
      transferredOwnershipEvent.OutputTuple,
      transferredOwnershipEvent.OutputObject
    >;
  };
}
