/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface DexhuneTokenRootInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "_holders"
      | "daoMintingStartsAfter"
      | "exchangeMintingStartsAfter"
      | "getOwner"
      | "mint"
      | "mintToDao"
      | "mintToExchange"
      | "mintingStartsAfter"
      | "setDaoAddress"
      | "setExchangeAddress"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "Alloc"): EventFragment;

  encodeFunctionData(
    functionFragment: "_holders",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "daoMintingStartsAfter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "exchangeMintingStartsAfter",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getOwner", values?: undefined): string;
  encodeFunctionData(functionFragment: "mint", values?: undefined): string;
  encodeFunctionData(functionFragment: "mintToDao", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "mintToExchange",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "mintingStartsAfter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setDaoAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setExchangeAddress",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "_holders", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "daoMintingStartsAfter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "exchangeMintingStartsAfter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getOwner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "mint", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "mintToDao", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "mintToExchange",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintingStartsAfter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDaoAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setExchangeAddress",
    data: BytesLike
  ): Result;
}

export namespace AllocEvent {
  export type InputTuple = [addr: AddressLike, funds: BigNumberish];
  export type OutputTuple = [addr: string, funds: bigint];
  export interface OutputObject {
    addr: string;
    funds: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DexhuneTokenRoot extends BaseContract {
  connect(runner?: ContractRunner | null): DexhuneTokenRoot;
  waitForDeployment(): Promise<this>;

  interface: DexhuneTokenRootInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  _holders: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  daoMintingStartsAfter: TypedContractMethod<[], [bigint], "view">;

  exchangeMintingStartsAfter: TypedContractMethod<[], [bigint], "view">;

  getOwner: TypedContractMethod<[], [string], "view">;

  mint: TypedContractMethod<[], [void], "nonpayable">;

  mintToDao: TypedContractMethod<[], [void], "nonpayable">;

  mintToExchange: TypedContractMethod<[], [void], "nonpayable">;

  mintingStartsAfter: TypedContractMethod<[], [bigint], "view">;

  setDaoAddress: TypedContractMethod<[addr: AddressLike], [void], "nonpayable">;

  setExchangeAddress: TypedContractMethod<
    [addr: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "_holders"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "daoMintingStartsAfter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "exchangeMintingStartsAfter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getOwner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "mint"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "mintToDao"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "mintToExchange"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "mintingStartsAfter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "setDaoAddress"
  ): TypedContractMethod<[addr: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setExchangeAddress"
  ): TypedContractMethod<[addr: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "Alloc"
  ): TypedContractEvent<
    AllocEvent.InputTuple,
    AllocEvent.OutputTuple,
    AllocEvent.OutputObject
  >;

  filters: {
    "Alloc(address,int128)": TypedContractEvent<
      AllocEvent.InputTuple,
      AllocEvent.OutputTuple,
      AllocEvent.OutputObject
    >;
    Alloc: TypedContractEvent<
      AllocEvent.InputTuple,
      AllocEvent.OutputTuple,
      AllocEvent.OutputObject
    >;
  };
}
