/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "DexhuneERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DexhuneERC20__factory>;
    getContractFactory(
      name: "DexhuneERC20Base",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DexhuneERC20Base__factory>;
    getContractFactory(
      name: "DexhuneExchange",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DexhuneExchange__factory>;
    getContractFactory(
      name: "IDexhuneExchange",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IDexhuneExchange__factory>;
    getContractFactory(
      name: "DexhuneExchangeBase",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DexhuneExchangeBase__factory>;
    getContractFactory(
      name: "DexhunePriceDAO",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DexhunePriceDAO__factory>;
    getContractFactory(
      name: "DexhunePriceDAOBase",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DexhunePriceDAOBase__factory>;
    getContractFactory(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC165__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "IERC721",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721__factory>;
    getContractFactory(
      name: "IPriceDAO",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IPriceDAO__factory>;
    getContractFactory(
      name: "MockNFT",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockNFT__factory>;
    getContractFactory(
      name: "ERC20Normalizer",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20Normalizer__factory>;
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;

    getContractAt(
      name: "DexhuneERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.DexhuneERC20>;
    getContractAt(
      name: "DexhuneERC20Base",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.DexhuneERC20Base>;
    getContractAt(
      name: "DexhuneExchange",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.DexhuneExchange>;
    getContractAt(
      name: "IDexhuneExchange",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IDexhuneExchange>;
    getContractAt(
      name: "DexhuneExchangeBase",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.DexhuneExchangeBase>;
    getContractAt(
      name: "DexhunePriceDAO",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.DexhunePriceDAO>;
    getContractAt(
      name: "DexhunePriceDAOBase",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.DexhunePriceDAOBase>;
    getContractAt(
      name: "IERC165",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC165>;
    getContractAt(
      name: "IERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "IERC721",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721>;
    getContractAt(
      name: "IPriceDAO",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IPriceDAO>;
    getContractAt(
      name: "MockNFT",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockNFT>;
    getContractAt(
      name: "ERC20Normalizer",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC20Normalizer>;
    getContractAt(
      name: "Ownable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;

    deployContract(
      name: "DexhuneERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DexhuneERC20>;
    deployContract(
      name: "DexhuneERC20Base",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DexhuneERC20Base>;
    deployContract(
      name: "DexhuneExchange",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DexhuneExchange>;
    deployContract(
      name: "IDexhuneExchange",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IDexhuneExchange>;
    deployContract(
      name: "DexhuneExchangeBase",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DexhuneExchangeBase>;
    deployContract(
      name: "DexhunePriceDAO",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DexhunePriceDAO>;
    deployContract(
      name: "DexhunePriceDAOBase",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DexhunePriceDAOBase>;
    deployContract(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC165>;
    deployContract(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "IERC721",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721>;
    deployContract(
      name: "IPriceDAO",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IPriceDAO>;
    deployContract(
      name: "MockNFT",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockNFT>;
    deployContract(
      name: "ERC20Normalizer",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20Normalizer>;
    deployContract(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable>;

    deployContract(
      name: "DexhuneERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DexhuneERC20>;
    deployContract(
      name: "DexhuneERC20Base",
      args: any[],
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DexhuneERC20Base>;
    deployContract(
      name: "DexhuneExchange",
      args: any[],
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DexhuneExchange>;
    deployContract(
      name: "IDexhuneExchange",
      args: any[],
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IDexhuneExchange>;
    deployContract(
      name: "DexhuneExchangeBase",
      args: any[],
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DexhuneExchangeBase>;
    deployContract(
      name: "DexhunePriceDAO",
      args: any[],
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DexhunePriceDAO>;
    deployContract(
      name: "DexhunePriceDAOBase",
      args: any[],
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DexhunePriceDAOBase>;
    deployContract(
      name: "IERC165",
      args: any[],
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC165>;
    deployContract(
      name: "IERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "IERC721",
      args: any[],
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721>;
    deployContract(
      name: "IPriceDAO",
      args: any[],
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IPriceDAO>;
    deployContract(
      name: "MockNFT",
      args: any[],
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockNFT>;
    deployContract(
      name: "ERC20Normalizer",
      args: any[],
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20Normalizer>;
    deployContract(
      name: "Ownable",
      args: any[],
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.Contract>;
  }
}
